databases:
  - name: qrcode-db
    databaseName: qrcode_db
    user: qrcode_app
    plan: free

services:
  - type: web
    name: qrcode-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: qrcode-db
          property: connectionString
